### PR TITLE
add confirm delete all dialog to shopping list + fix account bug

### LINKED ISSUE #41: Add dialog to confirm deletion of entire shopping list
A dialog box needs to be added when the user presses on the `Remove All Items` button. The dialog can display a message such as

```text
Are you sure you want to delete all items from your shopping list ? 
```

and can use an Alert icon to let the user know this is a serious action. Then if the user presses `Yes` it confirms the deletion of the list. 

Dialog example can be found [here](https://developer.android.com/develop/ui/compose/components/dialog#alert) .

### PR DESCRIPTION
**Pull request by evanhearne**
## What:

- Confirm Dialog for when a user wishes to delete their entire shopping list via `Delete All` button has been added. 
- Account Bug, where anonymous logins to display shopping item images via Firebase, meant that `Account` screen displayed `null` display name. This bug is now fixed.

## How:

- Alert Dialog with message `Your entire list will be deleted!` is implemented through boolean `showModal` on `ShoppingListScreen` . 
- Checks for `user.email` and `user.displayName` being `null` fixes the anonymous login being recognised as a valid user login. 

## Why:

- Alerts user of a more serious modification to their app. 
- User can now log in with their own account.

### CODE REVIEW

File: app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt [hunk 1]
```diff
@@ -45,6 +48,8 @@ import kotlinx.coroutines.tasks.await
 fun ShoppingListScreen(modifier: Modifier = Modifier, onNavigateBack: () -> Unit, shoppingListViewModel: ShoppingListViewModel, onItemClick: (ShoppingItem) -> Unit) {
     val scope = rememberCoroutineScope()
     val storage = Firebase.storage
+    // modal boolean
+    val showModal = remember { mutableStateOf(false) }
```
Comment (evanhearne) [inline app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt:52]: `showModal` is `displayModal` - replace in description to reflect true variable name.

File: app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt [hunk 2]
```diff
@@ -66,6 +71,47 @@ fun ShoppingListScreen(modifier: Modifier = Modifier, onNavigateBack: () -> Unit
                                  },
             )
         }
+        if (showModal.value) {
+            AlertDialog(
+                icon = {
+                    Icon(Icons.Default.Warning, contentDescription = "Warning Icon")
```
Comment (evanhearne) [inline app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt]: String should be converted to resource.

File: app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt [hunk 3]
```diff
@@ -66,6 +71,47 @@ fun ShoppingListScreen(modifier: Modifier = Modifier, onNavigateBack: () -> Unit
...
+                },
+                title = {
+                    Text(text = "Are you sure?")
```
Comment (evanhearne) [inline app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt]: Same here.

File: app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt [hunk 4]
```diff
@@ -66,6 +71,47 @@ fun ShoppingListScreen(modifier: Modifier = Modifier, onNavigateBack: () -> Unit
...
+                },
+                text = {
+                    Text(text = "Your entire list will be deleted!")
```
Comment (evanhearne) [inline app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt]: Same here.

**Review by evanhearne — COMMENTED** [review]
Amend changes and re-review.

File: app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt [hunk 5]
```diff
@@ -66,6 +71,47 @@ fun ShoppingListScreen(modifier: Modifier = Modifier, onNavigateBack: () -> Unit
...
+                            scope.launch {
+                                val email = Firebase.auth.currentUser?.email
+                                if (email != null)
+                                    shoppingListViewModel.removeAllItems(email)
+                                else
+                                    shoppingListViewModel.removeAllItems()
+                            }
+                        }
+                    ) {
+                        Text("Confirm")
```
Comment (evanhearne) [inline app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt]: Convert to string resource

File: app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt [hunk 6]
```diff
@@ -66,6 +71,47 @@ fun ShoppingListScreen(modifier: Modifier = Modifier, onNavigateBack: () -> Unit
...
+                    }
+                },
+                dismissButton = {
+                    TextButton(
+                        onClick = {
+                             showModal.value = !showModal.value
+                        }
+                    ) {
+                        Text("Dismiss")
```
Comment (evanhearne) [inline app/src/main/java/ie/setu/mad2_assignment_one/ui/shopping/ShoppingListScreen.kt]: Same here

**Review by evanhearne — COMMENTED** [review]
/lgtm but the commit msg is not great - ensure merge commit msg for main branch reflects changes...
